export default [
    {
      id: 0,
      name: '사다',
      mean: '값을 치르고 어떤 물건이나 권리를 자기 것으로 만들다.',
      explanation: '1·5지 끝을 맞대어 동그라미를 만든 오른손을, 손등이 위로 향하게 편 왼 손목 위에서 밖으로 내밀며 편다.',
      image_url: 'https://wis.seoul.go.kr/rest/file/download/fclpv1e4fghs7bha84cj4bwe4kxpjwmj/1',
      video_url: '',
    },
    {
      id: 1,
      name: '만나다',
      mean: '누군가 가거나 와서 둘이 서로 마주 보다.',
      explanation: '두 주먹의 1지를 펴서 마주 세웠다가 중앙으로 모아 마주 댄다.',
      image_url: 'https://wis.seoul.go.kr/rest/file/download/fclpv1e4fghs7bha84cj4bwe4kxpjwmj/1',
      video_url: '',
    },
    {
      id: 2,
      name: '먹다',
      mean: '누군가 가거나 와서 둘이 서로 마주 보다.',
      explanation: '두 주먹의 1지를 펴서 마주 세웠다가 중앙으로 모아 마주 댄다.',
      image_url: 'https://wis.seoul.go.kr/rest/file/download/fclpv1e4fghs7bha84cj4bwe4kxpjwmj/1',
      video_url: '',
    },
    {
      id: 3,
      name: '자다',
      mean: '누군가 가거나 와서 둘이 서로 마주 보다.',
      explanation: '두 주먹의 1지를 펴서 마주 세웠다가 중앙으로 모아 마주 댄다.',
      image_url: 'https://wis.seoul.go.kr/rest/file/download/fclpv1e4fghs7bha84cj4bwe4kxpjwmj/1',
      video_url: '',
    },
    {
      id: 4,
      name: '좋다',
      mean: '누군가 가거나 와서 둘이 서로 마주 보다.',
      explanation: '두 주먹의 1지를 펴서 마주 세웠다가 중앙으로 모아 마주 댄다.',
      image_url: 'https://wis.seoul.go.kr/rest/file/download/fclpv1e4fghs7bha84cj4bwe4kxpjwmj/1',
      video_url: '',
    },
    {
      id: 0,
      name: '사다',
      mean: '값을 치르고 어떤 물건이나 권리를 자기 것으로 만들다.',
      explanation: '1·5지 끝을 맞대어 동그라미를 만든 오른손을, 손등이 위로 향하게 편 왼 손목 위에서 밖으로 내밀며 편다.',
      image_url: 'https://wis.seoul.go.kr/rest/file/download/fclpv1e4fghs7bha84cj4bwe4kxpjwmj/1',
      video_url: '',
    },
    {
      id: 1,
      name: '만나다',
      mean: '누군가 가거나 와서 둘이 서로 마주 보다.',
      explanation: '두 주먹의 1지를 펴서 마주 세웠다가 중앙으로 모아 마주 댄다.',
      image_url: 'https://wis.seoul.go.kr/rest/file/download/fclpv1e4fghs7bha84cj4bwe4kxpjwmj/1',
      video_url: '',
    },
    {
      id: 2,
      name: '먹다',
      mean: '누군가 가거나 와서 둘이 서로 마주 보다.',
      explanation: '두 주먹의 1지를 펴서 마주 세웠다가 중앙으로 모아 마주 댄다.',
      image_url: 'https://wis.seoul.go.kr/rest/file/download/fclpv1e4fghs7bha84cj4bwe4kxpjwmj/1',
      video_url: '',
    },
    {
      id: 3,
      name: '자다',
      mean: '누군가 가거나 와서 둘이 서로 마주 보다.',
      explanation: '두 주먹의 1지를 펴서 마주 세웠다가 중앙으로 모아 마주 댄다.',
      image_url: 'https://wis.seoul.go.kr/rest/file/download/fclpv1e4fghs7bha84cj4bwe4kxpjwmj/1',
      video_url: '',
    },
    {
      id: 4,
      name: '좋다',
      mean: '누군가 가거나 와서 둘이 서로 마주 보다.',
      explanation: '두 주먹의 1지를 펴서 마주 세웠다가 중앙으로 모아 마주 댄다.',
      image_url: 'https://wis.seoul.go.kr/rest/file/download/fclpv1e4fghs7bha84cj4bwe4kxpjwmj/1',
      video_url: '',
    },
    {
        id: 0,
        name: '사다',
        mean: '값을 치르고 어떤 물건이나 권리를 자기 것으로 만들다.',
        explanation: '1·5지 끝을 맞대어 동그라미를 만든 오른손을, 손등이 위로 향하게 편 왼 손목 위에서 밖으로 내밀며 편다.',
        image_url: 'https://wis.seoul.go.kr/rest/file/download/fclpv1e4fghs7bha84cj4bwe4kxpjwmj/1',
        video_url: '',
      },
      {
        id: 1,
        name: '만나다',
        mean: '누군가 가거나 와서 둘이 서로 마주 보다.',
        explanation: '두 주먹의 1지를 펴서 마주 세웠다가 중앙으로 모아 마주 댄다.',
        image_url: 'https://wis.seoul.go.kr/rest/file/download/fclpv1e4fghs7bha84cj4bwe4kxpjwmj/1',
        video_url: '',
      },
      {
        id: 2,
        name: '먹다',
        mean: '누군가 가거나 와서 둘이 서로 마주 보다.',
        explanation: '두 주먹의 1지를 펴서 마주 세웠다가 중앙으로 모아 마주 댄다.',
        image_url: 'https://wis.seoul.go.kr/rest/file/download/fclpv1e4fghs7bha84cj4bwe4kxpjwmj/1',
        video_url: '',
      },
      {
        id: 3,
        name: '자다',
        mean: '누군가 가거나 와서 둘이 서로 마주 보다.',
        explanation: '두 주먹의 1지를 펴서 마주 세웠다가 중앙으로 모아 마주 댄다.',
        image_url: 'https://wis.seoul.go.kr/rest/file/download/fclpv1e4fghs7bha84cj4bwe4kxpjwmj/1',
        video_url: '',
      },
      {
        id: 4,
        name: '좋다',
        mean: '누군가 가거나 와서 둘이 서로 마주 보다.',
        explanation: '두 주먹의 1지를 펴서 마주 세웠다가 중앙으로 모아 마주 댄다.',
        image_url: 'https://wis.seoul.go.kr/rest/file/download/fclpv1e4fghs7bha84cj4bwe4kxpjwmj/1',
        video_url: '',
      },
      {
        id: 0,
        name: '사다',
        mean: '값을 치르고 어떤 물건이나 권리를 자기 것으로 만들다.',
        explanation: '1·5지 끝을 맞대어 동그라미를 만든 오른손을, 손등이 위로 향하게 편 왼 손목 위에서 밖으로 내밀며 편다.',
        image_url: 'https://wis.seoul.go.kr/rest/file/download/fclpv1e4fghs7bha84cj4bwe4kxpjwmj/1',
        video_url: '',
      },
  ]